//
// This is a generated file, do not edit!
// Generated by R.swift, see https://github.com/mac-cain13/R.swift
//

import Foundation
import Rswift
import UIKit

/// This `R` struct is generated and contains references to static resources.
struct R: Rswift.Validatable {
  fileprivate static let applicationLocale = hostingBundle.preferredLocalizations.first.flatMap(Locale.init) ?? Locale.current
  fileprivate static let hostingBundle = Bundle(for: R.Class.self)
  
  static func validate() throws {
    try intern.validate()
  }
  
  /// This `R.nib` struct is generated, and contains static references to 4 nibs.
  struct nib {
    /// Nib `LocationDetailView`.
    static let locationDetailView = _R.nib._LocationDetailView()
    /// Nib `LocationListView`.
    static let locationListView = _R.nib._LocationListView()
    /// Nib `LocationTableViewCell`.
    static let locationTableViewCell = _R.nib._LocationTableViewCell()
    /// Nib `TitleSubtitleTableViewCell`.
    static let titleSubtitleTableViewCell = _R.nib._TitleSubtitleTableViewCell()
    
    /// `UINib(name: "LocationDetailView", in: bundle)`
    @available(*, deprecated, message: "Use UINib(resource: R.nib.locationDetailView) instead")
    static func locationDetailView(_: Void = ()) -> UIKit.UINib {
      return UIKit.UINib(resource: R.nib.locationDetailView)
    }
    
    /// `UINib(name: "LocationListView", in: bundle)`
    @available(*, deprecated, message: "Use UINib(resource: R.nib.locationListView) instead")
    static func locationListView(_: Void = ()) -> UIKit.UINib {
      return UIKit.UINib(resource: R.nib.locationListView)
    }
    
    /// `UINib(name: "LocationTableViewCell", in: bundle)`
    @available(*, deprecated, message: "Use UINib(resource: R.nib.locationTableViewCell) instead")
    static func locationTableViewCell(_: Void = ()) -> UIKit.UINib {
      return UIKit.UINib(resource: R.nib.locationTableViewCell)
    }
    
    /// `UINib(name: "TitleSubtitleTableViewCell", in: bundle)`
    @available(*, deprecated, message: "Use UINib(resource: R.nib.titleSubtitleTableViewCell) instead")
    static func titleSubtitleTableViewCell(_: Void = ()) -> UIKit.UINib {
      return UIKit.UINib(resource: R.nib.titleSubtitleTableViewCell)
    }
    
    static func locationDetailView(owner ownerOrNil: AnyObject?, options optionsOrNil: [UINib.OptionsKey : Any]? = nil) -> UIKit.UIView? {
      return R.nib.locationDetailView.instantiate(withOwner: ownerOrNil, options: optionsOrNil)[0] as? UIKit.UIView
    }
    
    static func locationListView(owner ownerOrNil: AnyObject?, options optionsOrNil: [UINib.OptionsKey : Any]? = nil) -> UIKit.UIView? {
      return R.nib.locationListView.instantiate(withOwner: ownerOrNil, options: optionsOrNil)[0] as? UIKit.UIView
    }
    
    static func locationTableViewCell(owner ownerOrNil: AnyObject?, options optionsOrNil: [UINib.OptionsKey : Any]? = nil) -> LocationTableViewCell? {
      return R.nib.locationTableViewCell.instantiate(withOwner: ownerOrNil, options: optionsOrNil)[0] as? LocationTableViewCell
    }
    
    static func titleSubtitleTableViewCell(owner ownerOrNil: AnyObject?, options optionsOrNil: [UINib.OptionsKey : Any]? = nil) -> TitleSubtitleTableViewCell? {
      return R.nib.titleSubtitleTableViewCell.instantiate(withOwner: ownerOrNil, options: optionsOrNil)[0] as? TitleSubtitleTableViewCell
    }
    
    fileprivate init() {}
  }
  
  /// This `R.reuseIdentifier` struct is generated, and contains static references to 1 reuse identifiers.
  struct reuseIdentifier {
    /// Reuse identifier `LocationTableViewCell`.
    static let locationTableViewCell: Rswift.ReuseIdentifier<LocationTableViewCell> = Rswift.ReuseIdentifier(identifier: "LocationTableViewCell")
    
    fileprivate init() {}
  }
  
  /// This `R.storyboard` struct is generated, and contains static references to 1 storyboards.
  struct storyboard {
    /// Storyboard `LaunchScreen`.
    static let launchScreen = _R.storyboard.launchScreen()
    
    /// `UIStoryboard(name: "LaunchScreen", bundle: ...)`
    static func launchScreen(_: Void = ()) -> UIKit.UIStoryboard {
      return UIKit.UIStoryboard(resource: R.storyboard.launchScreen)
    }
    
    fileprivate init() {}
  }
  
  /// This `R.string` struct is generated, and contains static references to 2 localization tables.
  struct string {
    /// This `R.string.infoPlist` struct is generated, and contains static references to 1 localization keys.
    struct infoPlist {
      /// Value: Your location will be used to show your current distance to points of interest
      static let nsLocationWhenInUseUsageDescription = Rswift.StringResource(key: "NSLocationWhenInUseUsageDescription", tableName: "InfoPlist", bundle: R.hostingBundle, locales: [], comment: nil)
      
      /// Value: Your location will be used to show your current distance to points of interest
      static func nsLocationWhenInUseUsageDescription(_: Void = ()) -> String {
        return NSLocalizedString("NSLocationWhenInUseUsageDescription", tableName: "InfoPlist", bundle: R.hostingBundle, comment: "")
      }
      
      fileprivate init() {}
    }
    
    /// This `R.string.localizable` struct is generated, and contains static references to 7 localization keys.
    struct localizable {
      /// Value: Coordinates
      static let location_detail_coordinates = Rswift.StringResource(key: "location_detail_coordinates", tableName: "Localizable", bundle: R.hostingBundle, locales: [], comment: nil)
      /// Value: Distance
      static let location_detail_distance = Rswift.StringResource(key: "location_detail_distance", tableName: "Localizable", bundle: R.hostingBundle, locales: [], comment: nil)
      /// Value: Distance: %@
      static let location_cell_distance = Rswift.StringResource(key: "location_cell_distance", tableName: "Localizable", bundle: R.hostingBundle, locales: [], comment: nil)
      /// Value: Locations
      static let location_title = Rswift.StringResource(key: "location_title", tableName: "Localizable", bundle: R.hostingBundle, locales: [], comment: nil)
      /// Value: Postal Code
      static let location_detail_postalCode = Rswift.StringResource(key: "location_detail_postalCode", tableName: "Localizable", bundle: R.hostingBundle, locales: [], comment: nil)
      /// Value: Search locations
      static let location_search_placeholder = Rswift.StringResource(key: "location_search_placeholder", tableName: "Localizable", bundle: R.hostingBundle, locales: [], comment: nil)
      /// Value: Street
      static let location_detail_street = Rswift.StringResource(key: "location_detail_street", tableName: "Localizable", bundle: R.hostingBundle, locales: [], comment: nil)
      
      /// Value: Coordinates
      static func location_detail_coordinates(_: Void = ()) -> String {
        return NSLocalizedString("location_detail_coordinates", bundle: R.hostingBundle, comment: "")
      }
      
      /// Value: Distance
      static func location_detail_distance(_: Void = ()) -> String {
        return NSLocalizedString("location_detail_distance", bundle: R.hostingBundle, comment: "")
      }
      
      /// Value: Distance: %@
      static func location_cell_distance(_ value1: String) -> String {
        return String(format: NSLocalizedString("location_cell_distance", bundle: R.hostingBundle, comment: ""), locale: R.applicationLocale, value1)
      }
      
      /// Value: Locations
      static func location_title(_: Void = ()) -> String {
        return NSLocalizedString("location_title", bundle: R.hostingBundle, comment: "")
      }
      
      /// Value: Postal Code
      static func location_detail_postalCode(_: Void = ()) -> String {
        return NSLocalizedString("location_detail_postalCode", bundle: R.hostingBundle, comment: "")
      }
      
      /// Value: Search locations
      static func location_search_placeholder(_: Void = ()) -> String {
        return NSLocalizedString("location_search_placeholder", bundle: R.hostingBundle, comment: "")
      }
      
      /// Value: Street
      static func location_detail_street(_: Void = ()) -> String {
        return NSLocalizedString("location_detail_street", bundle: R.hostingBundle, comment: "")
      }
      
      fileprivate init() {}
    }
    
    fileprivate init() {}
  }
  
  fileprivate struct intern: Rswift.Validatable {
    fileprivate static func validate() throws {
      try _R.validate()
    }
    
    fileprivate init() {}
  }
  
  fileprivate class Class {}
  
  fileprivate init() {}
}

struct _R: Rswift.Validatable {
  static func validate() throws {
    try storyboard.validate()
  }
  
  struct nib {
    struct _LocationDetailView: Rswift.NibResourceType {
      let bundle = R.hostingBundle
      let name = "LocationDetailView"
      
      func firstView(owner ownerOrNil: AnyObject?, options optionsOrNil: [UINib.OptionsKey : Any]? = nil) -> UIKit.UIView? {
        return instantiate(withOwner: ownerOrNil, options: optionsOrNil)[0] as? UIKit.UIView
      }
      
      fileprivate init() {}
    }
    
    struct _LocationListView: Rswift.NibResourceType {
      let bundle = R.hostingBundle
      let name = "LocationListView"
      
      func firstView(owner ownerOrNil: AnyObject?, options optionsOrNil: [UINib.OptionsKey : Any]? = nil) -> UIKit.UIView? {
        return instantiate(withOwner: ownerOrNil, options: optionsOrNil)[0] as? UIKit.UIView
      }
      
      fileprivate init() {}
    }
    
    struct _LocationTableViewCell: Rswift.NibResourceType, Rswift.ReuseIdentifierType {
      typealias ReusableType = LocationTableViewCell
      
      let bundle = R.hostingBundle
      let identifier = "LocationTableViewCell"
      let name = "LocationTableViewCell"
      
      func firstView(owner ownerOrNil: AnyObject?, options optionsOrNil: [UINib.OptionsKey : Any]? = nil) -> LocationTableViewCell? {
        return instantiate(withOwner: ownerOrNil, options: optionsOrNil)[0] as? LocationTableViewCell
      }
      
      fileprivate init() {}
    }
    
    struct _TitleSubtitleTableViewCell: Rswift.NibResourceType {
      let bundle = R.hostingBundle
      let name = "TitleSubtitleTableViewCell"
      
      func firstView(owner ownerOrNil: AnyObject?, options optionsOrNil: [UINib.OptionsKey : Any]? = nil) -> TitleSubtitleTableViewCell? {
        return instantiate(withOwner: ownerOrNil, options: optionsOrNil)[0] as? TitleSubtitleTableViewCell
      }
      
      fileprivate init() {}
    }
    
    fileprivate init() {}
  }
  
  struct storyboard: Rswift.Validatable {
    static func validate() throws {
      try launchScreen.validate()
    }
    
    struct launchScreen: Rswift.StoryboardResourceWithInitialControllerType, Rswift.Validatable {
      typealias InitialController = UIKit.UIViewController
      
      let bundle = R.hostingBundle
      let name = "LaunchScreen"
      
      static func validate() throws {
        if #available(iOS 11.0, *) {
        }
      }
      
      fileprivate init() {}
    }
    
    fileprivate init() {}
  }
  
  fileprivate init() {}
}
